### ISSUE TITLE
HttpErrorResponse while parsing a JSON file

### ISSUE THREAD

**Issue by Bendrog** [SoatGroup/ionic3-movie-app#1]
I followed your tutorial for a personnal project (thanks it is really well done and detailed)

So I created a list of troupeau in the page 'searching.html'. It works perfectly when my troupeaux are created in "searching.ts" but it fail when it comes from a JSON file...

Here is what my console gives me:
HttpErrorResponse {headers: HttpHeaders, status: 200, statusText: "OK", url: "http://localhost:8100/assets/api/troupeaux.json", ok: false, …}
error
:
error
:
SyntaxError: Unexpected token } in JSON at position 347 at JSON.parse (<anonymous>) at XMLHttpRequest.onLoad (http://localhost:8100/build/vendor.js:71581:51) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660) at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5125:33) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581) at r.runTask (http://localhost:8100/build/polyfills.js:3:10834) at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16794) at p (http://localhost:8100/build/polyfills.js:2:27648) at XMLHttpRequest.v (http://localhost:8100/build/polyfills.js:2:27893)
text
:
"[
↵	{
↵		"id":"14863",
↵		"EDE": 53176211,
↵		"etab": "GAEC DE BARADABA",
    ... blablabla .... { the hole troupeau.json file }

I do not know in which file is the error happening. I guess it is an error from node Module as it is not a GET error. 

my project is available in this link: =>  https://github.com/Bendrog/IonicApp
_______________________________________________________________________________________________________________
So if I compare my project to your's : 

. movie-list == searching
. movie-api == rest
. movies.json == troupeaux.json
. IMovie.ts == Troupeaux.ts
_______________________________________________________________________________________________________________

Do you have any idea?

**Comment by LamineMbn** [comment]
Hey @Bendrog, I just created a pull request on your project. Your json wasn't valid that's all (I hope :stuck_out_tongue_closed_eyes: )

**Comment by Bendrog** [comment]
Hi @LamineMbn  thank you for your comit, that was it !
I didn't know that json syntax was this strict

You made my day  :)

**Comment by LamineMbn** [comment]
ahaha, happy to help :smile:
